#ifndef BASELINE_CONFIG_HPP
#define BASELINE_CONFIG_HPP

#define BASELINE_WANT_SERIAL
#define BASELINE_WANT_BLE_DEVICE
#define BASELINE_WANT_WIFI_AP
#define BASELINE_WANT_WIFI_STA

#endif // BASELINE_CONFIG_HPP
